name: diary_app
description: "some diary notes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.2.2
  flutter_launcher_icons: ^0.14.2
  intl: ^0.19.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/icon.png
    - assets/icon/emotions/happy.png
    - assets/icon/emotions/sad.png
    - assets/icon/emotions/angry.png
    - assets/icon/emotions/excited.png
    - assets/icon/emotions/calm.png
    - assets/icon/emotions/default.png
    - assets/icon/emotions/exhausted.png
    - assets/icon/emotions/stressed.png
  fonts:
    - family: StrangeFont
      fonts:
        - asset: assets/fonts/Playwrite_HR_Lijeva/static/PlaywriteHRLijeva-Regular.ttf

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

  android: "launcher_icon"
  image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true
