/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/geolocation-search`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/requests`; params?: Router.UnknownInputParams; } | { pathname: `/today`; params?: Router.UnknownInputParams; } | { pathname: `/weekly`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useLocation`; params?: Router.UnknownInputParams; } | { pathname: `/utils/parseInfo`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/constants`; params?: Router.UnknownOutputParams; } | { pathname: `/geolocation-search`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/requests`; params?: Router.UnknownOutputParams; } | { pathname: `/today`; params?: Router.UnknownOutputParams; } | { pathname: `/weekly`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useLocation`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/parseInfo`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/constants${`?${string}` | `#${string}` | ''}` | `/geolocation-search${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/requests${`?${string}` | `#${string}` | ''}` | `/today${`?${string}` | `#${string}` | ''}` | `/weekly${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/hooks/useLocation${`?${string}` | `#${string}` | ''}` | `/utils/parseInfo${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/geolocation-search`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/requests`; params?: Router.UnknownInputParams; } | { pathname: `/today`; params?: Router.UnknownInputParams; } | { pathname: `/weekly`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useLocation`; params?: Router.UnknownInputParams; } | { pathname: `/utils/parseInfo`; params?: Router.UnknownInputParams; };
    }
  }
}
